AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  alpaca-trading

  Sample SAM Template for alpaca-trading

Globals:
  Function:
    Timeout: 180

Parameters:
  BucketName:
    Type: String
    Default: tempalpacatraderbucket
  AlapcaId:
    Type: String
    Default: alpacaid
  AlpacaSecret:
    Type: String
    Default: alpacasecret
  FinnhubToken:
    Type: String
    Default: finnhubtoken
#  SplunkAccessToken:
#    Type: String
#    Default: splunk-token
#  Realm:
#    Type: String
#    Default: realm
#  Environment:
#    Type: String
#    Default: environment
#  SplunkOtelLayer:
#    Type: String
#    Default: arn:aws:lambda:us-east-1:254067382080:layer:splunk-apm:62

Resources:
  AlpacaTraderBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicReadWrite
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: stockTraderLambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AWSLambda_FullAccess'
  WatchListUpdaterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WatchListUpdater
      Role: !GetAtt LambdaRole.Arn
      CodeUri: watchlist_updater/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment:
        Variables:
#          SPLUNK_ACCESS_TOKEN: !Ref SplunkAccessToken
#          SPLUNK_REALM: !Ref Realm
#          OTEL_SERVICE_NAME: watchlistUpdater
#          OTEL_RESOURCE_ATTRIBUTES: !Ref Environment
#          AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
          BUCKET_NAME: !Ref BucketName
          ALPACA_ID: !Ref AlapcaId
          ALPACA_SECRET: !Ref AlpacaSecret
      Events:
        WatchListUpdater:
          Type: Api
          Properties:
            Path: /watchlistupdate
            Method: get
      Layers:
        - !Ref Libs
#        - !Ref SplunkOtelLayer
#        - 'arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-pandas:7'
#        - 'arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-requests:1'
  StockRankerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StockRankerFunction
      Role: !GetAtt LambdaRole.Arn
      CodeUri: stock_ranker/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
#          SPLUNK_ACCESS_TOKEN: !Ref SplunkAccessToken
#          SPLUNK_REALM: !Ref Realm
#          OTEL_SERVICE_NAME: stockRanker
#          OTEL_RESOURCE_ATTRIBUTES: !Ref Environment
#          AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
          BUCKET_NAME: !Ref BucketName
          GET_FIN_FUNC_NAME: GetFinancials
      Architectures:
        - x86_64
      Events:
        StockRankerEvent:
          Type: Api
          Properties:
            Path: /stockranker
            Method: get
      Layers:
        - !Ref Libs
#        - !Ref SplunkOtelLayer
#        - 'arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-pandas:7'
  GetFinancialsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetFinancials
      Role: !GetAtt LambdaRole.Arn
      CodeUri: ./get_financials
      Runtime: python3.8
      Handler: app.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
#          SPLUNK_ACCESS_TOKEN: !Ref SplunkAccessToken
#          SPLUNK_REALM: !Ref Realm
#          OTEL_SERVICE_NAME: getFinancials
#          OTEL_RESOURCE_ATTRIBUTES: !Ref Environment
#          AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
          BUCKET_NAME: !Ref BucketName
          FINNHUB_TOKEN: !Ref FinnhubToken
      Events:
        GetFinancials:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /getfinancials
            Method: get
      Layers:
        - !Ref Libs
#        - !Ref SplunkOtelLayer
#        - 'arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-requests:1'
  BuyStocksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BuyStocks
      Role: !GetAtt LambdaRole.Arn
      CodeUri: ./buy_stocks
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment:
        Variables:
#          SPLUNK_ACCESS_TOKEN: !Ref SplunkAccessToken
#          SPLUNK_REALM: !Ref Realm
#          OTEL_SERVICE_NAME: buyStocks
#          OTEL_RESOURCE_ATTRIBUTES: !Ref Environment
#          AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
          BUCKET_NAME: !Ref BucketName
          ALPACA_ID: !Ref AlapcaId
          ALPACA_SECRET: !Ref AlpacaSecret
      Events:
        BuyStocksEvent:
          Type: Api
          Properties:
            Path: /buystocks
            Method: get
      Layers:
        - !Ref Libs
#        - !Ref SplunkOtelLayer
#        - 'arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-pandas:7'
#        - 'arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-requests:1'
  Libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SharedLibs
      ContentUri: libs
      CompatibleRuntimes:
        - python3.8
      CompatibleArchitectures:
        - x86_64
    Metadata:
      BuildMethod: python3.8

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  WatchListUpdaterFunctionArn:
    Description: "Watchlist Updater Function ARN"
    Value: !GetAtt WatchListUpdaterFunction.Arn
  StockRankerFunctionArn:
    Description: "Stock Ranker FunctionARN"
    Value: !GetAtt StockRankerFunction.Arn